config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items, only:[:new, :show, :destroy,:create,:edit, :update] do
    member do
      get 'buy'
      get 'confirm'
      get 'children'
      get 'grandchildren'
    end
    collection do
      get "search"
      get 'children', defaults: { format: 'json' }
      get 'grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :users, only: [:show]
  
  get "category_parent", to: "categories#parent"
  get "category_child", to: "categories#child"
  get "category_grand_child", to: "categories#grand_child"
end
   

app/views/module/_footer.html.haml
.footer
  .footer__top
    .footer__top__content
      .footer__top__content__head
        = "FURIMAについて"
      .footer__top__content__bottom
        .footer__top__content__bottom__list
          = link_to "会社概要（運営会社）"
        .footer__top__content__bottom__list
          = link_to "プライバシーポリシー"
        .footer__top__content__bottom__list
          = link_to "FURIMA利用規約"
        .footer__top__content__bottom__list
          = link_to "ポイントに関する特約"
    .footer__top__content
      .footer__top__content__head
        = "FURIMAを見る"
      .footer__top__content__bottom
        .footer__top__content__bottom__list
          = link_to "カテゴリー一覧"
        .footer__top__content__bottom__list
          = link_to "ブランド一覧"
    .footer__top__content
      .footer__top__content__head
        = "ヘルプ＆ガイド"
      .footer__top__content__bottom
        .footer__top__content__bottom__list
          = link_to "FURIMAガイド"
        .footer__top__content__bottom__list
          = link_to "FURIMAロゴ利用ガイドライン"
        .footer__top__content__bottom__list
          = link_to "お知らせ"
  .footer__logo
    = link_to image_tag "logo-white.png",width:"160px"
  .footer__copy-light
    = "@FURIMA"

app/views/module/_header.html.haml
.header
  .header__main
    .header__main__top
      .header__main__top__logo
        = link_to image_tag("logo.png", width:"140px"), '/'
      .header__main__top__form
        = form_tag({controller: "items", action: "search" }, method: :get) do
          .header__main__top__form__box
            = text_field_tag :search, "", {placeholder: "キーワードから探す",class:"header__main__top__form__box__text"}
            = image_submit_tag "icon-search 1.png",class:"header__main__top__form__box__submit",width:"30px"
    .header__main__bottom
      .header__main__bottom__left
        .header__main__bottom__left__cate
          = link_to "カテゴリー"
          -# = link_to "カテゴリー", category_parent_path, class: "rootCategory"
          -# .parents_list
          -# .children_list
          -# .grand_children_list
          
        .header__main__bottom__left__brand
          = link_to "ブランド"
      .header__main__bottom__right
        - if user_signed_in?
          .header__main__bottom__right__logout
            = link_to "ログアウト",destroy_user_session_path
          .header__main__bottom__right__mypage
            = link_to "#{current_user.last_name+current_user.first_name}のページ",user_path(current_user.id)
        - else
          .header__main__bottom__right__login
            = link_to "ログイン",new_user_session_path
          .header__main__bottom__right__new
            = link_to "新規会員登録", new_user_registration_path
    