config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items, only:[:new, :show, :destroy,:create,:edit, :update] do
    member do
      get 'buy'
      get 'confirm'
      get 'children'
      get 'grandchildren'
    end
    collection do
      get "search"
      get 'children', defaults: { format: 'json' }
      get 'grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :users, only: [:show]
  
  get "category_parent", to: "categories#parent"
  get "category_child", to: "categories#child"
  get "category_grand_child", to: "categories#grand_child"
end
   

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  has_one :card
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :first_name, :last_name, :first_hurigana, :last_hurigana, :birthday, :postcode, :prefecture, :city, :block, :password, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validate :zenkaku_first_name, :zenkaku_last_name

  def zenkaku_first_name
    if first_name !~/^[^ -~｡-ﾟ]*$/
      errors.add(:zenkaku_first_name, "全角ではありません") # error message
    end
  end
  
  def zenkaku_last_name
    if last_name !~/^[^ -~｡-ﾟ]*$/
      errors.add(:zenkaku_last_name, "全角ではありません") # error message
    end
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @items = Item.where(user_id: @user.id)
    @item = Item.find(params[:id])
    @photos = @item.photos
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
.items
  .show 
    = render partial:"module/header"
    - breadcrumb :mypage
    = render "layouts/breadcrumbs"

.users
  .show
    .wrapper
      .main
        .main__profilebox
          .main__profilebox__image
          %h2.main__profilebox__name
            = @user.last_name+@user.first_name  # 出品者名
          .main__profilebox__score
            .main__profilebox__score__review
            %p 評価100
            .main__profilebox__score__number
            %p="出品数#{@items.count}"

        .main__stampbox
          .main__stampbox__stamps
            .main__stampbox__stamps__goodbox
              .main__stampbox__stamps__goodbox__icon
                %i.far.fa-laugh-squint{color: "pink"}
              .main__stampbox__stamps__goodbox__number
                %p 50
            .main__stampbox__stamps__normalbox
              .main__stampbox__stamps__normalbox__icon
                %i.far.fa-laugh
              .main__stampbox__stamps__normalbox__number
                %p 50
            .main__stampbox__stamps__badbox
              .main__stampbox__stamps__badbox__icon
                %i.far.fa-tired
              .main__stampbox__stamps__badbox__number
                50
        .main__itembox
          .main__itembox__header
            この出品者の商品
          .main__itembox__itemsbox
            .main__itembox__itemsbox__room
              .main__itembox__itemsbox__room__item
                = image_tag ("a004.png"), size: "200x220"
              .main__itembox__itemsbox__room__detail
                .main__itembox__itemsbox__room__detail__name
                  アイテム
                .main__itembox__itemsbox__room__detail__price-box
                  .main__itembox__itemsbox__room__detail__price-box__price
                    1000円
                  .main__itembox__itemsbox__room__detail__price-box__icon
                    %i.far.fa-heart 30
             

          %a{:href => "items/new"}
        .purchaseBtn
          %span.purchaseBtn__text 出品する
          = link_to image_tag("icon_camera.png", alt: "アップルリンク画像", class: "purchaseBtn__icon")

        .purchaseBtn1
          %span.purchaseBtn1__text
            = link_to "カード登録", new_card_path
          %span.purchaseBtn1__text
            = link_to "カード確認", card_path
          = image_tag 'card_icon.png', class: "purchaseBtn1__icon"
        
          




.items
  .show
    = render partial:"module/footer"            