config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items, only:[:new, :show, :destroy,:create,:edit, :update] do
    member do
      get 'buy'
      get 'confirm'
      get 'children'
      get 'grandchildren'
    end
    collection do
      get "search"
      get 'children', defaults: { format: 'json' }
      get 'grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :users, only: [:show]
  
  get "category_parent", to: "categories#parent"
  get "category_child", to: "categories#child"
  get "category_grand_child", to: "categories#grand_child"
end
   

app/models/item.rb
class Item < ApplicationRecord
  has_many :photos, dependent: :destroy
  belongs_to :user
  belongs_to :category
  accepts_nested_attributes_for :photos,allow_destroy: true 
  validates :name, :text, :condition, :burden, :area, :day, :price, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.where(buyer: nil).order(id:"DESC")
    @photos = Photo.all
  end

  def new
    @item = Item.new
    @photos = @item.photos.new
    @categories = Category.where(ancestry: nil)
    
  end


  def children
    @children = Category.where(ancestry: params[:parent_name])
  end


  def grandchildren
    @grandchildren = Category.where(['ancestry LIKE ?', "%#{params[:child_name]}%"])
  end


  def create
    if  @item = Item.new(item_params)
      @item.save
      redirect_to root_path
    else
      flash[:notice] = "完了しておりません"
    end
  end

 


  def show
    @item = Item.find(params[:id])
    @area = Area.find(@item.area)
    @photos = @item.photos
    @user = @item.user
    @grandchild = Category.find(@item.category_id)  
    @grandchildren = @grandchild.siblings
    @child = @grandchild.parent
    @parent = @child.parent
    @children = @child.siblings
    @parents = @parent.siblings
  end


  def confirm
    @item = Item.find(params[:id])
    @photos = @item.photos
    @user = @item.user
  end

  def buy
    @item = Item.find(params[:id])
    @item.update(buyer: current_user.id)

    card = Card.find_by(user_id: current_user.id)
    if card == nil
      redirect_to new_card_path
      flash[:noCard] = "Cardが登録されていませんので登録してください"
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
      Payjp::Charge.create(
        amount: @item.price, # Payjpに載る金額
        customer: card.customer_id, # 顧客ID
        currency: 'jpy'
      )
      redirect_to '/'
      flash[:notice] = "購入が完了しました"
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to '/'
  end


  def edit
    @categories = Category.where(ancestry: nil)
    @item = Item.find(params[:id])
    @photos = @item.photos
    @user = @item.user
    @grandchild = Category.find(@item.category_id)    
    @grandchildren = @grandchild.siblings
    @child = @grandchild.parent
    @parent = @child.parent
    @children = @child.siblings
    @parents = @parent.siblings
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  def search
    @items = Item.where(['name like ?', "%#{params[:search]}%"])
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :text,:condition,:burden, :area, :day, :price, :category_id, :user_id, :buyer , photos_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/confirm.html.haml
-# 購入確認画面作成2020/1/30(後で正式なコントローラーへ変更する)
.items
  .confirm
    .buy
      .buy__header
        = link_to image_tag( "logo", size: "260x85", alt: "商品画像"), '/'
      .buy__wrraper
        .buy__head--title
          購入内容の確認
        .buy__second
          .buy__second--image
            = image_tag ("#{@photos.find_by(item_id:params[:id]).image}"), size:"100x90"
          .buy__second--price
            %p.buy__second--price--name
              = @item.name
            %p.buy__second--price--price
              = "価格:¥#{@item.price}"
        .buy__third
          .buy__third--price
            %p.buy__third--price--text 
              支払金額
            %p.buy__third--price--int
              = "¥#{@item.price}"
          .buy__third--red
            %p ※お支払方法はクレジットカードのみになります
          .buy__third--address
            %p.postcode= "〒#{@user.postcode}"
            %p.city= "発送元：#{@user.prefecture + @user.city + @user.block}"
            %p.name= "出品者：#{@user.last_name + @user.first_name}"
            .buy__third--address--red 
              %p 配送方法 : ラクラクフリマ便

          .buy__third--address--btn
            .mini
              = link_to "購入する", buy_item_path(id: @item.id), class:"buy-btn"

            
          .buy__third--address--comment
            %p アプリをお持ちでない方は以下よりインストールしてご利用いただけます
            .buy__third--address--image1
              = link_to image_tag("app-store", size: "150x100", alt: "アップルリンク画像")
              = link_to image_tag( "google-play", size: "150x100", alt: "グーグルリンク画像")    
          .foot
            .foot__link
              %tr=link_to "プライバシーポリシー", url:'#'
              %tr=link_to "フリマ利用規約", url:'#'
              %tr=link_to "特定商取引に関する表記", url:'#'
            .foot__icon
              = image_tag "logo-white", size: "260x75", alt: "商品画像"
            

    
      

app/views/items/edit.html.haml
.items
  .notification
    - if flash[:notice]
      %p= flash[:notice]
  .edit
    .header
      = image_tag "logo.png", size: "185x49"
    .contents
      = form_for @item do |f|
        .contents__header
          商品の情報を入力
        .contents__image
          .contents__image__top
            .contents__image__top__font
              出品画像
            .contents__image__top__required
              必須
          .contents__image__text
            最大10枚までアップロードします
          .contents__image__form
            .contents__image__form__text
              -@photos.each_with_index do |p,i|
                = image_tag ("#{p.image}"),width:"100px",height:"100px" 
              %b
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
              #image-box
                = f.fields_for :photos do |i|
                  .contents__image__form__text__js-file_group{data:{index:i.index}}
                    = i.file_field :image,class:"contents__image__form__text__js-file_group__file"
                    .js-remove 削除
                  - if @item.persisted?
                    = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
                - if @item.persisted?
                  .contents__image__form__text__js-file_group{data:{index:"#{@photos.count}"}}
                    = file_field_tag :image, name: "item[photos_attributes][#{@photos.count}][image]",class:"contents__image__form__text__js-file_group__file"
                    .js-remove 削除       
          .contents__name__top
            .contents__name__top__font
              商品名
            .contents__name__top__required
              必須
          = f.text_field :name,class:"contents__name__field",placeholder:"商品名(必須40文字まで)"
        .contents__explain
          .contents__explain__top
            .contents__explain__top__font
              商品説明
            .contents__explain__top__required
              必須
          = f.text_area :text,class:"contents__explain__area",placeholder:"商品名 （商品の説明(必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）   2010年頃に1万円に購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。）"
        .contents__detail
          .contents__detail__main
            .contents__detail__main__name
              商品の詳細
            .contents__detail__main__box
              .contents__detail__main__box__cate
                .contents__detail__main__box__cate__top
                  .contents__detail__main__box__cate__top__font
                    カテゴリー
                  .contents__detail__main__box__cate__top__required
                    必須
                = f.collection_select :category_id,@categories, :id, :name,{prompt: "---"},class:"contents__detail__main__box__cate__select",id:"parent_category"
                = f.collection_select :category_id,@children, :id, :name,{prompt: "---"},class:"contents__detail__main__box__cate__select",id:"edit-children"
                = f.collection_select :category_id,@grandchildren, :id, :name,{prompt: "---"},class:"contents__detail__main__box__cate__select",id:"edit-grandchildren"
              .contents__detail__main__box__condition
                .contents__detail__main__box__condition__top
                  .contents__detail__main__box__condition__top__font
                    商品の状態
                  .contents__detail__main__box__condition__top__required
                    必須
                = f.select :condition, [ ["新品、未使用","新品、未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れなし", "やや傷や汚れなし"], ["傷や汚れなし", "傷や汚れなし"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"] ], {prompt: "---"}, class:"contents__detail__main__box__condition__select"
        .contents__deal
          .contents__deal__main
            .contents__deal__main__name
              配送について
            .contents__deal__main__box
              .contents__deal__main__box__burden
                .contents__deal__main__box__burden__top
                  .contents__deal__main__box__burden__top__font
                    配送料の負担
                  .contents__deal__main__box__burden__top__required
                    必須
                = f.select :burden, [ ["送料込み(出品者負担)",1], ["着払い(購入者負担)", 2] ], {prompt: "---"}, class:"contents__deal__main__box__burden__select"
              .contents__deal__main__box__area
                .contents__deal__main__box__area__top
                  .contents__deal__main__box__area__top__font
                    発想元の地域
                  .contents__deal__main__box__area__top__required
                    必須
                = f.collection_select :area, Area.all,:id, :name, {prompt: "---"}, class:"contents__deal__main__box__area__select" 
              .contents__deal__main__box__days
                .contents__deal__main__box__days__top
                  .contents__deal__main__box__days__top__font
                    発送までの日数
                  .contents__deal__main__box__days__top__required
                    必須
                = f.select :day, [ ["1~2日で発送","1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"] ], {prompt: "---"}, class:"contents__deal__main__box__days__select"
        .contents__money
          .contents__money__main
            .contets__money__main__name
              販売価格(300~9,999,999)
            .contents__money__main__box
              .contents__money__main__box__frame
                .contents__money__main__box__frame__left
                  .contents__money__main__box__frame__left__top
                    .contents__money__main__box__frame__left__top__font
                      価格
                    .contents__money__main__box__frame__left__top__required
                      必須
                .contents__money__main__box__frame__right
                  .contents__money__main__box__frame__right__yen
                    ¥
                = f.text_field :price,class:"contents__money__main__box__frame__right__price",placeholder: '  例）  300'
        .contents__text
          .contents__text__main
            .contents__text__main__first
              = link_to '禁止されている出品', '/#', class: 'contents__text__main__first__box1'
              、
              = link_to '行為', '/#', class: 'contents__text__main__first__box2'
              を必ずご確認ください。
            .contents__text__main__second
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to '偽ブランドの販売', '/#', class: 'contents__text__main__second__box1'
              は犯罪であり処罰される可能性があります。
            .contents__text__main__third{}
              また、出品をもちまして
              = link_to '加盟店規約', '/#', class: 'contents__text__main__third__box1'
              に同意したことになります。
        .contents__submit
          .contents__submit__sell
            = f.submit "変更する", class: 'contents__submit__sell__button'
          .contents__submit__back
            = link_to 'もどる',root_path, class: 'contents__submit__back__button'
    .footer
      = link_to 'プライバシーポリシー', '/#', class: 'footer__left'
      = link_to 'メルカリ利用規約', '/#', class: 'footer__middle'
      = link_to '特定商取引に関する表記', '/#', class: 'footer__right'
      .footer__logo
        = image_tag "logo-white.png", size: "120x70"
      %small © FURIMA, Inc.

app/views/items/index.html.haml
.items
  .notification
    - if flash[:notice]
      %p= flash[:notice]
  .show
    = render partial: 'module/header'
.items
  .index
    .index-contents
      .index-contents__visual
        .index-contents__visual__main
          .index-contents__visual__main__subtitle
            %h2 
              %br  人生を変えるフリマアプリ 
          %p.index-contents__visual__main__text
            FURIMAはだれでもかんたんに出品・購入できる
            %br/
            フリマアプリです
          .index-contents__visual__main__btn
            .index-contents__visual__main__btn__applebox
              = link_to image_tag("app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", alt: "アップルリンク画像")
            .index-contents__visual__main__btn__googlebox
              = link_to image_tag("google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", alt: "グーグルリンク画像")
        .index-contents__visual__picture
      .index-contents__introduction
        %h2.index-contents__introduction__subtitle
          FURIMAが選ばれる3つの理由
        %ul.index-contents__introduction__lists
          %li.index-contents__introduction__lists__list
            .index-contents__introduction__lists__list__pict
              %span.index-contents__introduction__lists__list__pict__number 1
              = image_tag "pict-reason-01.jpg",alt: "",size:"306x306"
            %h3.index-contents__introduction__lists__list__text
              %span 3分
              ですぐに出品
            %p.index-contents__introduction__lists__list__description
              スマホで入力するだけで簡単に出品できる！
          %li.index-contents__introduction__lists__list
            .index-contents__introduction__lists__list__pict
              %span.index-contents__introduction__lists__list__pict__number 2
              = image_tag "pict-reason-02.jpg",alt: "",size:"306x306"
            %h3.index-contents__introduction__lists__list__text
              %span シンプル
              で使いやすい
            %p.index-contents__introduction__lists__list__description
              めんどくさい入力は必要なく、検索も購入もスムーズ！
          %li.index-contents__introduction__lists__list-last
            .index-contents__introduction__lists__list-last__pict
              %span.index-contents__introduction__lists__list-last__pict__number 3
              = image_tag "pict-reason-03.jpg",alt: "",size:"306x306"
            %h3.index-contents__introduction__lists__list-last__text
              手数料
              %span 業界最安
            %p.index-contents__introduction__lists__list-last__description
              最大3%でお得に出品&amp;購入！
      .index-contents__middledi
        .index-contents__middledi__inner
          %h2.index-contents__middledi__inner__subtitle 会員数日本一位
          %p.index-contents__middledi__inner__text
            FURIMAは、フリマアプリで最も人気。
            %br/
            出品・購入回数も業界最多です！
            %br/
            ほしかったあの商品に出会えるかもしれません。
          .index-contents__middledi__inner__btn
            .index-contents__middledi__inner__btn__applebox
              = link_to image_tag("app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", alt: "アップルリンク画像")
            .index-contents__middledi__inner__btn__googlebox
              = link_to image_tag("google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", alt: "グーグルリンク画像")
      .index-contents__keyfeatures
        %h2.index-contents__keyfeatures__head FURIMAの特徴
        .index-contents__keyfeatures__items
          %section.index-contents__keyfeatures__items__item
            %figure.index-contents__keyfeatures__items__item__img
              = image_tag "icon-01.png",alt: "",size:"306x306"
            %h3.index-contents__keyfeatures__items__item__subtitle 簡単に売り買いできる
            %p.index-contents__keyfeatures__items__item__detail
              スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
          %section.index-contents__keyfeatures__items__item
            %figure.index-contents__keyfeatures__items__item__img
              = image_tag "icon-02.png",alt: "",size:"306x306"
            %h3.index-contents__keyfeatures__items__item__subtitle 売上金は即日振込みに対応
            %p.index-contents__keyfeatures__items__item__detail
              午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
          %section.index-contents__keyfeatures__items__item
            %figure.index-contents__keyfeatures__items__item__img
              = image_tag "icon-03.png",alt: "",size:"306x306"
            %h3.index-contents__keyfeatures__items__item__subtitle 様々な支払いに対応
            %p.index-contents__keyfeatures__items__item__detail
              お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
      %section.index-contents__pickupContainer
        %h2.index-contents__pickupContainer__head ピックアップカテゴリー
        .index-contents__pickupContainer__productBox
          .index-contents__pickupContainer__productBox__productHead
            %h3.index-contents__pickupContainer__productBox__productHead__title 新規投稿商品
          .index-contents__pickupContainer__productBox__productLists
            - @items.first(3).each do |t|
              .index-contents__pickupContainer__productBox__productLists__productList
                %figure.index-contents__pickupContainer__productBox__productLists__productList__img
                  = link_to item_path(t.id) do
                    = image_tag ("#{@photos.find_by(item_id:t.id).image}")
                .index-contents__pickupContainer__productBox__productLists__productList__body
                  %h3.index-contents__pickupContainer__productBox__productLists__productList__body__name
                    = t.name
                  .index-contents__pickupContainer__productBox__productLists__productList__body__details
                    %ul
                      %li 
                        = "¥#{t.price}"
                      %li
                        %i.fas.fa-star
                        0
                    %p (税込)
      %section.index-contents__pickupContainer
        %h2.index-contents__pickupContainer__head ピックアップブランド
        .index-contents__pickupContainer__productBox
          .index-contents__pickupContainer__productBox__productHead
            %a{:href => "#"}
              %h3.index-contents__pickupContainer__productBox__productHead__title アーカイバ
          .index-contents__pickupContainer__productBox__productLists
            - @items.first(3).each do |t|
              .index-contents__pickupContainer__productBox__productLists__productList
                %figure.index-contents__pickupContainer__productBox__productLists__productList__img
                  = link_to item_path(t.id) do
                    = image_tag ("#{@photos.find_by(item_id:t.id).image}")
                .index-contents__pickupContainer__productBox__productLists__productList__body
                  %h3.index-contents__pickupContainer__productBox__productLists__productList__body__name
                    = t.name
                  .index-contents__pickupContainer__productBox__productLists__productList__body__details
                    %ul
                      %li 
                        = "¥#{t.price}"
                      %li
                        %i.fas.fa-star
                        0
                    %p (税込)
      .banner
        .banner__inner
          %h2.banner__inner__title だれでもかんたん、人生を変えるフリマアプリ
          %p.banner__inner__text 今すぐ無料ダウンロード！
          .banner__inner__icon
            .banner__inner__icon__applebox
              = link_to image_tag("app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", alt: "アップルリンク画像")
            .banner__inner__icon__googlebox
              = link_to image_tag("google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", alt: "グーグルリンク画像")
      .purchaseBtn
        %span.purchaseBtn__text 出品する
        = link_to image_tag("icon_camera.png", class: "purchaseBtn__icon"), "items/new"
  .show
    = render partial: 'module/footer'

    

app/views/items/new.html.haml
.items
  .new
    .header
      = image_tag "logo.png", size: "185x49"
    = form_for @item do |f|
      .contents
        .contents__header
          商品の情報を入力
        .contents__image
          .contents__image__top
            .contents__image__top__font
              出品画像
            .contents__image__top__required
              必須
          .contents__image__text
            最大10枚までアップロードします
          .contents__image__main
            -# .contents__image__main__box
            -#   .contents__image__main__box__image
            -#   .contents__image__main__box__btns
            -#     .contents__image__main__box__btns__remove
            -# .contents__image__main__left
              -# .contents__image__main__left__box
              -#   .contents__image__main__left__box__image
                -# .contents__image__main__left__box__btns
                -#   .contents__image__main__left__box__btns__remove
            %label.contents__image__main__right#label{for: "item_photos_attributes_0_image"}
              #image-box
                = f.fields_for :photos do |i|
                  .contents__image__main__right__group{data:{index:i.index}}
                    = i.file_field :image,class:"contents__image__main__right__group__file"
                  = "画像を選択"
        .contents__name
          .contents__name__top
            .contents__name__top__font
              商品名
            .contents__name__top__required
              必須
          = f.text_field :name,class:"contents__name__field",placeholder:"商品名(必須40文字まで)"
        .contents__explain
          .contents__explain__top
            .contents__explain__top__font
              商品説明
            .contents__explain__top__required
              必須
          = f.text_area :text,class:"contents__explain__area",placeholder:"商品名 （商品の説明(必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）   2010年頃に1万円に購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。）"
        .contents__detail
          .contents__detail__main
            .contents__detail__main__name
              商品の詳細
            .contents__detail__main__box
              .contents__detail__main__box__cate
                .contents__detail__main__box__cate__top
                  .contents__detail__main__box__cate__top__font
                    カテゴリー
                  .contents__detail__main__box__cate__top__required
                    必須
                = f.collection_select :category_id, @categories, :id, :name,{prompt: "---"},class:"contents__detail__main__box__cate__select",id:"parent_category"
              .contents__detail__main__box__condition
                .contents__detail__main__box__condition__top
                  .contents__detail__main__box__condition__top__font
                    商品の状態
                  .contents__detail__main__box__condition__top__required
                    必須
                = f.select :condition, [ ["新品、未使用","新品、未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れなし", "やや傷や汚れなし"], ["傷や汚れなし", "傷や汚れなし"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"] ], {prompt: "---"}, class:"contents__detail__main__box__condition__select"
        .contents__deal
          .contents__deal__main
            .contents__deal__main__name
              配送について
            .contents__deal__main__box
              .contents__deal__main__box__burden
                .contents__deal__main__box__burden__top
                  .contents__deal__main__box__burden__top__font
                    配送料の負担
                  .contents__deal__main__box__burden__top__required
                    必須
                = f.select :burden, [ ["送料込み(出品者負担)",1], ["着払い(購入者負担)", 2] ], {prompt: "---"}, class:"contents__deal__main__box__burden__select"
              .contents__deal__main__box__area
                .contents__deal__main__box__area__top
                  .contents__deal__main__box__area__top__font
                    発送元の地域
                  .contents__deal__main__box__area__top__required
                    必須
               
                = f.collection_select :area,Area.all, :id, :name,{prompt: "---"}, class:"contents__deal__main__box__area__select"

              .contents__deal__main__box__days
                .contents__deal__main__box__days__top
                  .contents__deal__main__box__days__top__font
                    発送までの日数
                  .contents__deal__main__box__days__top__required
                    必須
                = f.select :day, [ ["1~2日で発送","1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"] ], {prompt: "---"}, class:"contents__deal__main__box__days__select"
        .contents__money
          .contents__money__main
            .contets__money__main__name
              販売価格(300~9,999,999)
            .contents__money__main__box
              .contents__money__main__box__frame
                .contents__money__main__box__frame__left
                  .contents__money__main__box__frame__left__top
                    .contents__money__main__box__frame__left__top__font
                      価格
                    .contents__money__main__box__frame__left__top__required
                      必須
                .contents__money__main__box__frame__right
                  .contents__money__main__box__frame__right__yen
                    ¥
                = f.text_field :price,class:"contents__money__main__box__frame__right__price",placeholder: '  例）  300'
        .contents__text
          .contents__text__main
            .contents__text__main__first
              = link_to '禁止されている出品', '/#', class: 'contents__text__main__first__box1'
              、
              = link_to '行為', '/#', class: 'contents__text__main__first__box2'
              を必ずご確認ください。
            .contents__text__main__second
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to '偽ブランドの販売', '/#', class: 'contents__text__main__second__box1'
              は犯罪であり処罰される可能性があります。
            .contents__text__main__third{}
              また、出品をもちまして
              = link_to '加盟店規約', '/#', class: 'contents__text__main__third__box1'
              に同意したことになります。
        .contents__submit
          .contents__submit__sell
            = f.submit "出品する", class: 'contents__submit__sell__button'
          .contents__submit__back
            = link_to 'もどる',root_path, class: 'contents__submit__back__button'
    .footer
      = link_to 'プライバシーポリシー', '/#', class: 'footer__left'
      = link_to 'メルカリ利用規約', '/#', class: 'footer__middle'
      = link_to '特定商取引に関する表記', '/#', class: 'footer__right'
      .footer__logo
        = image_tag "logo-white.png", size: "120x70"
      %small © FURIMA, Inc.



    -# -# .header
    -# -#   = image_tag "logo.png", size: "185x49"
    -# -# .contents
    -# -#   = form_for @item do |f|
    -# -#     .contents__header
    -#       商品の情報を入力
    -#     .contents__image
    -#       .contents__image__top
    -#         .contents__image__top__font
    -#           出品画像
    -#         .contents__image__top__required
    -#           必須
    -#       .contents__image__text
    -#         最大10枚までアップロードします
    -#       .contents__image__form
    -#         .contents__image__form__text
    -#           %br
    -#             ドラッグアンドドロップ
    -#             %br
    -#             またはクリックしてファイルをアップロード
              -# #image-box
              -#   = f.fields_for :photos do |i|
              -#     .contents__image__form__text__js-file_group{data:{index:i.index}}
              -#       = i.file_field :image,class:"contents__image__form__text__js-file_group__file"
              -#       .js-remove{data:{index:i.index}}　削除

-# .item
-#   .new
-#     = form_for @item do |f|
-#     .contents
-#       .contents__left
-#       %label.contents__right
-#         #image-box
-#           = f.fields_for :photos do |i|
-#             .contents__right__group{data:{index:i.index}}
-#               = i.file_field :name,class:"contents__right__group__file"
-#             = "ドラッグアンドドロップ "
-#       .contents__left2
-#       %label.contents__right
-#         #image-box
-#           = f.fields_for :photos do |i|
-#             .contents__right__group{data:{index:i.index}}
-#               = i.file_field :name,class:"contents__right__group__file"
-#             = "ドラッグアンドドロップ "
    -# = form_for @item do |f|
    -#   .contents__header
    -#     商品の情報を入力
    -#   .contents__image
    -#     .contents__image__top
    -#       .contents__image__top__font
    -#         出品画像
    -#       .contents__image__top__required
    -#         必須
    -#     .contents__image__text
    -#       最大10枚までアップロードします
    -#     .contents__image__form
    -#       .contents__image__form__text
    -#         %br
    -#           ドラッグアンドドロップ
    -#           %br
    -#           またはクリックしてファイルをアップロード
    -#         #image-box
    -#           = f.fields_for :photos do |i|
    -#             .contents__image__form__text__js-file_group{data:{index:i.index}}
    -#               = i.file_field :image,class:"contents__image__form__text__js-file_group__file"
    -#               .js-remove{data:{index:i.index}}　削除

app/views/items/search.html.haml
.items
  .show
    = render partial:"module/header"
.search
  - @items.each do |i|
    .search__box
      .search__box__name
        = i.name
      .search__box__image
        = link_to item_path(i.id)do
          = image_tag "#{Photo.find_by(item_id: i.id).image}",width:"100px",height:"100px"

.items
  .show
    = render partial:"module/footer"