config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items, only:[:new, :show, :destroy,:create,:edit, :update] do
    member do
      get 'buy'
      get 'confirm'
      get 'children'
      get 'grandchildren'
    end
    collection do
      get "search"
      get 'children', defaults: { format: 'json' }
      get 'grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :users, only: [:show]
  
  get "category_parent", to: "categories#parent"
  get "category_child", to: "categories#child"
  get "category_grand_child", to: "categories#grand_child"
end
   

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :customer_id, :card_id, :user_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :set_card, only: [:new, :delete, :show]

  def new
    if @card.present?
      redirect_to card_path(id: @card.user_id)
    end
  end

  def create #PayjpとCardのデータベースを作成
    Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      # トークンが正常に発行されていたら、顧客情報をPAY.JPに登録します。
      customer = Payjp::Customer.create(
        description: 'test', # 無くてもOK。PAY.JPの顧客情報に表示する概要です。
        email: current_user.email,
        card: params['payjp-token'], # 直前のnewアクションで発行され、送られてくるトークンをここで顧客に紐付けて永久保存します。
        metadata: {user_id: current_user.id} # 無くてもOK。
      )
    end
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to cards_path(id: @card.user_id)
      else
        redirect_to action: "create"
      end
  end

  def show #Cardのデータをpayjpに送り情報を取り出します
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def delete #PayjpとCardデータベースを削除します
    if @card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "new"
  end

  private

    def set_card
      if Card.where(user_id: current_user.id).present?
      @card = current_user.card
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.notification
  - if flash[:noCard]
    %p= flash[:noCard]
.items
  .show 
    = render partial:"module/header"
.card
  = form_with url: "/cards/create", method: :post, html: { name: "inputForm" } do |f| # createアクションのパスを指定
    .wrapper
      .header
        クレジットカード情報入力
      .main
        .smallbox
          必須
        .main__numberbox
          %p カード番号 
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .cardimages
            = image_tag 'card.png',size: '200x70'
          %br/  
          %br
        .smallbox
          必須
        .main__deadline
          %p 有効期限
          .main__deadline__box
            %select#exp_month{name: "exp_month", type: "text",class: 'main__deadline__box1'}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月/
            %select#exp_year{name: "exp_year", type: "text",class: 'main__deadline__box2'}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年
          %br
        .smallbox__security 
          必須
        .main__security 
          %p セキュリティコード
          .main__security__box
            = text_field_tag "cvc", "", class: "main__security__box", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
            .main__security__box__add
              #card_token
              = f.submit '追加する', class: 'main__security__box__add', id: 'token_submit'
.items
  .show
    = render partial:"module/footer"            

app/views/cards/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する
= link_to "トップへ", '/'